# 应用服务 WEB 访问端口
server:
  address: 0.0.0.0
  port: 8107
  servlet:
    context-path: /api/notice
    session:
      cookie:
        max-age: 2592000
        path: /api

spring:
  application:
    name: competition-backend-notification-service
  servlet:
    multipart:
      max-file-size: 20MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9097
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition
    username: root
    password: as90976789
  redis:
    database: 1
    host: 192.168.59.226
    port: 6379
    timeout: 5000
  main:
    allow-bean-definition-overriding: true
  # 邮箱服务
  mail:
    host: smtp.163.com
    username: you_email@example.com
    password: YOUR_PASSWORD
    defaultEncoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          stattls:
            require: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true