# 应用服务 WEB 访问端口
server:
  address: 0.0.0.0
  port: 8110
  servlet:
    context-path: /api/content
    session:
      cookie:
        max-age: 2592000
        path: /api

spring:
  profiles:
    active: dev
  application:
    name: competition-backend-content-service
  servlet:
    multipart:
      max-file-size: 20MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8071
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition
    username: root
    password: as123456789
  redis:
    database: 1
    host: 192.168.59.226
    port: 6379
    timeout: 5000
knife4j:
  enable: true
